language: cpp

branches:
  only:
    - 6.0-dev

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check

script: ./autogen.sh && ./configure --with-check && make && make check -k && make distcheck

compiler:
  - clang
  - gcc

notifications:
  email:
    - torquedev@supercluster.org
